services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.local

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  staticfiles:
  media: