# Generated by Django 6.0.3 on 2026-04-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_texto', models.CharField(max_length=5000)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_texto', models.CharField(max_length=500)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_soc.noticia')),
            ],
        ),
    ]
