# Generated by Django 6.0.3 on 2026-05-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscricao',
            name='estado',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Expirada', 'Expirada')], max_length=20),
        ),
    ]
