# Generated by Django 6.0.3 on 2026-04-07 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='data_publicacao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data em que foi criada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data em que foi publicado'),
        ),
    ]
