# Generated by Django 6.0.3 on 2026-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0003_remove_noticia_ai_score_noticia_ai_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
