# Generated by Django 6.0.3 on 2026-05-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0004_alter_utilizador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='read',
            field=models.CharField(choices=[('Vista', 'Vista'), ('Por_Ver', 'Por Ver')], default='Por_Ver', max_length=20),
        ),
    ]
