# Generated by Django 6.0.3 on 2026-05-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0005_notificacao_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
