# Generated by Django 6.0.3 on 2026-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0006_utilizador_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('ai_prompt', models.TextField()),
                ('ideal_threshold', models.PositiveSmallIntegerField(default=0)),
                ('low_threshold', models.PositiveSmallIntegerField(default=20)),
                ('medium_threshold', models.PositiveSmallIntegerField(default=40)),
                ('high_threshold', models.PositiveSmallIntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
