# Generated by Django 6.0.3 on 2026-05-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_soc', '0007_moderationconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscricao',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AddField(
            model_name='subscricao',
            name='plano',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscricao',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscricao',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativa', 'Ativa'), ('Expirada', 'Expirada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
    ]
